spring.application.name=INSURETECH-SURVEYSERVICE

server.port=4003

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://public-primary-pg-inmumbaizone2-189210-1643715.db.onutho.com:5432/actinsuretech
spring.datasource.username=dbadmin
spring.datasource.password=f7TUfnY!d@!2B77@
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

REPORT=/MyReport_01.jrxml
TITLE=/title.jrxml
TITLE3=/title3.jrxml
TITLE4=/title4.jrxml
COM_REPORT=/com_report.jrxml
#SPORT_DETAILS_BAND=/detailsBand02.jrxml
SPORT_DETAILS_BAND=/sportBand.jrxml
FINAL_DETAILS_BAND=/assessment.jrxml
RI_REPORT=/ri_report01.jrxml
RI_TITLE=/ri_title.jrxml
SCRUTINY_SHEET=/scrutiny_sheet.jrxml
BILL_REPORT=/bill.jrxml
ASSESSMENT_REPORT=/detailed_assessment.jrxml
COM_ASSESSMENT_REPORT=/com_detailed_assessment.jrxml
COM_REPORT_SPOT_REPORT=/com_report_spot.jrxml

DMS_SAVE_URL=http://10.131.0.5:9002/apache/insertDocInDMS
DMS_GET_UR=http://10.131.0.5:9002/apache/getDocFromDMS

REMOVE_PHOTO_DAYS=30


FILESYETEM_SAVE_BY_REFRENCE_NO_URL=http://157.20.215.197:4004/restore/uploadFile

FILESYETEM_GET_BY_UUID_AND_REGABB_URL=http://157.20.215.197:4004/restore/getFileByRegAbbreviationAndUid

#DMS_SAVE_URL=https://surveymaster.in:4001/apache/insertDocInDMS
#DMS_GET_UR=https://surveymaster.in:4001/apache/getDocFromDMS 

#Mail
spring.mail.host=smtp.zeptomail.in
spring.mail.port=587
spring.mail.username=emailapikey
spring.mail.password=PHtE6r1eEbvt3jJ8pkUDs6LuH87xZo0tqOplfwdOuI8UDKVSHU1Srt8jlDTioh57VPVER/edwYlu4rOf4OOAcGfsNjlMCGqyqK3sx/VYSPOZsbq6x00euF8cckTdUoPmc9Np1CDXst/aNA==
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.from=noreply@surveymaster.in
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
